#:kivy 2.3.1
<RootWidget>:
    Button:
        id: botonazo
        text: "Imagenes"
        size_hint: (None, None)
        
    Button:
        text: "gris"
        size_hint: (None, None)
    Button:
        text: "negado"
        size_hint: (None, None)
    Button:
        text: "sepia"
        size_hint: (None, None)
    TextInput:
        size_hint: (None, None)

    Button:
        text: "Guardar"
        size_hint: (None, None)
    